---
spring.profiles: test2

spring.datasource:
    url: jdbc:mysql://localhost:3306/learnspringdatajpa
    driverClassName: com.mysql.jdbc.Driver
    username: arahansa
    password: 1234
spring.jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    ddl-auto: create-drop

---
spring.profiles: test

spring.datasource:
    url: jdbc:h2:tcp://localhost/~/learnspringdatajpa;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

---
spring.profiles: local

spring.datasource:
    url: jdbc:h2:~/learningspringdatajpa;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create-drop
